/*
 * Copyright (C) Contributors to the Suwayomi project
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

export type MUILocale = (typeof MUI_LOCALES)[number];

/**
 * **IMPORTANT:**
 *
 * This is generated by the `mui:gen-locales-array` script
 */
export const MUI_LOCALES = [
    'am-ET',
    'ar-EG',
    'ar-SA',
    'ar-SD',
    'az-AZ',
    'bn-BD',
    'be-BY',
    'bg-BG',
    'ca-ES',
    'cs-CZ',
    'da-DK',
    'de-DE',
    'el-GR',
    'en-US',
    'es-ES',
    'et-EE',
    'fa-IR',
    'fi-FI',
    'fr-FR',
    'he-IL',
    'hi-IN',
    'hr-HR',
    'hu-HU',
    'hy-AM',
    'id-ID',
    'is-IS',
    'it-IT',
    'ja-JP',
    'kh-KH',
    'ko-KR',
    'ku-CKB',
    'ku-Latn',
    'kk-KZ',
    'mk-MK',
    'my-MY',
    'ms-MS',
    'ne-NP',
    'nb-NO',
    'nn-NO',
    'nl-NL',
    'pl-PL',
    'ps-AF',
    'pt-BR',
    'pt-PT',
    'ro-RO',
    'sr-RS',
    'ru-RU',
    'si-LK',
    'sk-SK',
    'sv-SE',
    'th-TH',
    'tr-TR',
    'tl-TL',
    'uk-UA',
    'ur-PK',
    'vi-VN',
    'zh-CN',
    'zh-HK',
    'zh-TW',
] as const;
