/*
 * Copyright (C) Contributors to the Suwayomi project
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

import { enUS, Localization } from '@mui/material/locale';
import { MUI_LOCALES, MUILocale } from '@/lib/mui/Locales.ts';

const localeNameToImportName = (locale: MUILocale): string => locale.split('-').join('');

export const getMuiLocale = (locale: string): MUILocale => {
    if (MUI_LOCALES.includes(locale as MUILocale)) {
        return locale as MUILocale;
    }

    if (MUI_LOCALES.includes(locale.toLowerCase() as MUILocale)) {
        return locale.toLowerCase() as MUILocale;
    }

    const convertedLocale = locale.split('-')[0].toLowerCase();
    if (MUI_LOCALES.includes(convertedLocale as MUILocale)) {
        return convertedLocale as MUILocale;
    }

    return 'en-US';
};

export const importMUILocale = async (locale: string): Promise<Localization> => {
    const muiLocale = getMuiLocale(locale);

    try {
        // eslint-disable-next-line @typescript-eslint/no-use-before-define
        return ((await localesToImport[muiLocale]()) as any)[localeNameToImportName(muiLocale)];
    } catch (e) {
        // ignore and return default language
    }

    return enUS;
};

/**
 * **IMPORTANT:**
 *
 * This is generated by the `mui:gen-locales-imports` script
 */
const localesToImport: Record<(typeof MUI_LOCALES)[number], () => Promise<unknown>> = {
    'am-ET': () => import('@mui/material/locale'),
    'ar-EG': () => import('@mui/material/locale'),
    'ar-SA': () => import('@mui/material/locale'),
    'ar-SD': () => import('@mui/material/locale'),
    'az-AZ': () => import('@mui/material/locale'),
    'bn-BD': () => import('@mui/material/locale'),
    'be-BY': () => import('@mui/material/locale'),
    'bg-BG': () => import('@mui/material/locale'),
    'ca-ES': () => import('@mui/material/locale'),
    'cs-CZ': () => import('@mui/material/locale'),
    'da-DK': () => import('@mui/material/locale'),
    'de-DE': () => import('@mui/material/locale'),
    'el-GR': () => import('@mui/material/locale'),
    'en-US': () => import('@mui/material/locale'),
    'es-ES': () => import('@mui/material/locale'),
    'et-EE': () => import('@mui/material/locale'),
    'fa-IR': () => import('@mui/material/locale'),
    'fi-FI': () => import('@mui/material/locale'),
    'fr-FR': () => import('@mui/material/locale'),
    'he-IL': () => import('@mui/material/locale'),
    'hi-IN': () => import('@mui/material/locale'),
    'hr-HR': () => import('@mui/material/locale'),
    'hu-HU': () => import('@mui/material/locale'),
    'hy-AM': () => import('@mui/material/locale'),
    'id-ID': () => import('@mui/material/locale'),
    'is-IS': () => import('@mui/material/locale'),
    'it-IT': () => import('@mui/material/locale'),
    'ja-JP': () => import('@mui/material/locale'),
    'kh-KH': () => import('@mui/material/locale'),
    'ko-KR': () => import('@mui/material/locale'),
    'ku-CKB': () => import('@mui/material/locale'),
    'ku-Latn': () => import('@mui/material/locale'),
    'kk-KZ': () => import('@mui/material/locale'),
    'mk-MK': () => import('@mui/material/locale'),
    'my-MY': () => import('@mui/material/locale'),
    'ms-MS': () => import('@mui/material/locale'),
    'ne-NP': () => import('@mui/material/locale'),
    'nb-NO': () => import('@mui/material/locale'),
    'nn-NO': () => import('@mui/material/locale'),
    'nl-NL': () => import('@mui/material/locale'),
    'pl-PL': () => import('@mui/material/locale'),
    'ps-AF': () => import('@mui/material/locale'),
    'pt-BR': () => import('@mui/material/locale'),
    'pt-PT': () => import('@mui/material/locale'),
    'ro-RO': () => import('@mui/material/locale'),
    'sr-RS': () => import('@mui/material/locale'),
    'ru-RU': () => import('@mui/material/locale'),
    'si-LK': () => import('@mui/material/locale'),
    'sk-SK': () => import('@mui/material/locale'),
    'sv-SE': () => import('@mui/material/locale'),
    'th-TH': () => import('@mui/material/locale'),
    'tr-TR': () => import('@mui/material/locale'),
    'tl-TL': () => import('@mui/material/locale'),
    'uk-UA': () => import('@mui/material/locale'),
    'ur-PK': () => import('@mui/material/locale'),
    'vi-VN': () => import('@mui/material/locale'),
    'zh-CN': () => import('@mui/material/locale'),
    'zh-HK': () => import('@mui/material/locale'),
    'zh-TW': () => import('@mui/material/locale'),
};
